
services:
  backend:
      build:
        context: ./server
        dockerfile: server.Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./server:/app
      environment:
        NODE_ENV: production

  frontend:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules  # Prevents node_modules overwrite
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enables file watching inside Docker
    depends_on:
      - backend
