
services:
  backend:
      build:
        context: ./server
        dockerfile: server.Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./server:/app
      environment:
        NODE_ENV: production

  frontend:
    build: 
      context: ./client
      dockerfile: client.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
